### ISSUE TITLE
0.0.11 Version has Breaking Changes Requiring Turbo >8.0.0

### ISSUE THREAD

**Issue by Monica-Nguyen** [rails/request.js#78]
Logging this was visibility - There was a change added [here](https://github.com/rails/request.js/pull/74/files#diff-14a5bc0861a6d3817f577829f329b5b080409aa42d91e9d31aca88ba7a86567eR23) that uses `window.Turbo.fetch` but fetch was only added as part of Turbo >8.0.0 so our requests were failing with `window.Turbo.fetch` being undefined 

Can we update the release for 0.0.11 for higher visibility on the Turbo 8 requirement?

**Comment by marcelolx** [comment]
Thanks @Monica-Nguyen, I have updated the release to mention this breaking change https://github.com/rails/request.js/releases/tag/v0.0.11

I think we could have avoided it by changing the check from this 
```javascript
(this.responseKind === 'turbo-stream' && window.Turbo)
```

to 

```javascript
(this.responseKind === 'turbo-stream' && window.Turbo && window.Turbo.hasOwnProperty('fetch'))
```

However, since we already have those versions requiring Turbo 8, we will keep it as it is.
